### ISSUE TITLE
phpBB 3.2.7 login changes break extension

### ISSUE THREAD

**Issue by ianhiddleston** [Flerex/linkedaccounts#18]
It looks like the authentication changes in 3.2.7 cause you to be logged out instead of switched to the linked account.

**Comment by ianhiddleston** [comment]
Stack trace:
#0 /home/fnh/public_html/Boards/cache/production/container_4335734bbdd20f586549a504dff5f80c.php(2521): flerex\linkedaccounts\service\utils->__construct(Object(phpbb\user), Object(phpbb\db\driver\factory), 'phpbb_flerex_li...')
#1 /home/fnh/public_html/Boards/vendor/symfony/dependency-injection/Container.php(295): phpbb_cache_container->getFlerex_Linkedaccounts_UtilsService()
#2 /home/fnh/public_html/Boards/vendor/symfony/dependency-injection/ContainerBuilder.php(446): Symfony\Component\DependencyInjection\Container->get('flerex.linkedac...', 2)
#3 /home/fnh/public_html/Boards/cache/production/container_4335734bbdd20f58654 in /home/fnh/public_html/Boards/ext/flerex/linkedaccounts/service/utils.php on line 35

**Comment by ianhiddleston** [comment]
phpBB version 3.2.7
Linked Account version 1.2.1
Default theme is prosilver (hopefully won't matter)
Also have the following enabled:

Application Form | 1.0.7
Board Announcements | 1.1.0
Large Font | 3.2.0
Linked Accounts | 1.2.1
Name Suggestions | 1.0.1
Pages | 2.0.3
phpBB SiteMaker | 3.1.1
Post Edit Log | 1.2.0
Topic Preview | 2.3.0

I've tried to disable, clear cache, enable, clear cache. Before and after I just get dropped out to the main login page if I switch between linked accounts. Previously (phpBB 3.2.5) I would be switched seamlessly between accounts.

**Comment by ianhiddleston** [comment]
Scratch that, it was a caching issue, possibly client side. I've just gone back through the clear and enable steps, then rechecked with a completely fresh machine and things appear to be working.
